WITH BIKE AS (

    SELECT 
    START_STATIO_ID AS STATION_ID,
    START_STATION_NAME AS STATION_NAME,
    START_LAT AS START_STATION_LAT,
    START_LNG AS START_STATION_LNG
 
    FROM {{ source('DEMO', 'BIKE') }}
     WHERE START_STATIO_ID != 'start station id'        
)
SELECT * FROM BIKE
