WITH TRIPS as (
select
    RIDE_ID,
    DATE(TRY_TO_TIMESTAMP(STARTED_AT)) AS TRIP_DATE,
    START_STATIO_ID AS START_STATION_ID,
    END_STATION_ID,
    MEMBER_CSUAL AS MEMBER_CASUAL,
    DATEDIFF(SECOND,TRY_TO_TIMESTAMP(STARTED_AT),TRY_TO_TIMESTAMP(ENDED_AT)) AS TRIP_DURATION_SECONDS
from {{ source('DEMO', 'BIKE') }}
where RIDE_ID != 'ride_id'

)

select
*
from TRIPS
